spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1018
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
server:
  port: 8080
jwt:
  token:
    header: Authorization
    issuer: Modu_Point
    clientSecret: aa64eb33e4701c204be9ca4b16c488eee31ae31cb561b1f5f50f6c7b63d14cb1
    expirySeconds: 3600